import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { userCheckoutOrder, pawaPayCheckoutOrder } from './orderController.js';
import User from '../models/userModel.js';
import Product from '../models/productModel.js';
import Cart from '../models/cartModel.js';
import Order from '../models/orderModel.js';
import City from '../models/cityModel.js';
import Commune from '../models/communeModel.js';
import * as config from '../services/configService.js';
import * as provider from '../services/pawapayService.js';
import * as attribution from '../services/socialCommerce/attributionService.js';
import * as bundles from '../services/bundleService.js';
import * as visibility from '../utils/publicProductVisibility.js';
import * as notifications from '../utils/notificationService.js';
import * as escrow from '../services/escrowService.js';
import * as completion from '../services/orderCheckoutCompletionService.js';
const buyer = 'bbbbbbbbbbbbbbbbbbbbbbbb', seller = 'aaaaaaaaaaaaaaaaaaaaaaaa', country = 'cccccccccccccccccccccccc';
const cityId = 'dddddddddddddddddddddddd', communeId = 'eeeeeeeeeeeeeeeeeeeeeeee', productId = '111111111111111111111111';
const response = () => ({ status: vi.fn().mockReturnThis(), json: vi.fn().mockReturnThis() });
const product = { _id: productId, user: { _id: seller, name: 'Boutique' }, countryId: country, currency: 'XAF', status: 'approved', title: 'Article', price: 10000, attributes: [], images: [], deliveryAvailable: true, pickupAvailable: true, deliveryFeeEnabled: true, deliveryFee: 750 };
beforeEach(() => {
  vi.spyOn(completion, 'completeOrderCheckoutOnce').mockImplementation(async ({ createOrders }) => ({ orders: await createOrders(null), created: true }));
  vi.spyOn(provider, 'getPawaPayConfig').mockReturnValue({ exclusiveMode: true });
  vi.spyOn(config, 'getRuntimeConfig').mockImplementation(async (key, { fallback } = {}) => key === 'enable_pay_for_other' ? true : fallback);
  vi.spyOn(attribution, 'resolveAttributionForOrder').mockResolvedValue({});
  vi.spyOn(bundles, 'applyBundleDiscountsForSellers').mockResolvedValue();
  vi.spyOn(visibility, 'getVerifiedProductIds').mockResolvedValue([productId]);
  vi.spyOn(User, 'findById').mockReturnValue({ select: async () => ({ _id: buyer, name: 'Client', phone: '+242060000001' }) });
  vi.spyOn(User, 'findOne').mockReturnValue({ select: async () => ({ _id: '999999999999999999999999', name: 'Proche', phone: '+242060000002' }) });
  vi.spyOn(User, 'find').mockReturnValue({ select: () => ({ lean: async () => [{ _id: seller }] }) });
  vi.spyOn(Cart, 'findOne').mockReturnValue({ lean: async () => ({ _id: 'cart', user: buyer, countryId: country, currency: 'XAF', items: [{ product: productId, quantity: 1 }] }) });
  vi.spyOn(Cart, 'updateOne').mockResolvedValue({});
  vi.spyOn(Product, 'find').mockReturnValue({ populate: async () => [product], lean: async () => [product] });
  vi.spyOn(Order, 'findOne').mockResolvedValue(null);
  vi.spyOn(Order, 'deleteMany').mockResolvedValue({});
  vi.spyOn(Order, 'create').mockImplementation(async value => Array.isArray(value) ? value.map((row, index) => ({ ...row, _id: `order${index}` })) : { ...value, _id: 'order' });
  vi.spyOn(notifications, 'createNotification').mockResolvedValue();
  vi.spyOn(escrow, 'recordEscrowAudit').mockResolvedValue();
  vi.spyOn(City, 'findOne').mockReturnValue({ lean: async () => ({ _id: cityId, name: 'Brazzaville' }) });
  vi.spyOn(Commune, 'findOne').mockReturnValue({ lean: async () => ({ _id: communeId, cityId, name: 'Poto-Poto' }) });
});
afterEach(() => vi.restoreAllMocks());
describe('checkout respects service settings', () => {
  it('creates an unpaid sponsorship while manual payments remain blocked', async () => {
    const req = { user: { _id: buyer }, countryContext: { countryId: country, code: 'CG' }, body: { sponsorship: { payerPhone: '+242060000002' }, deliveryMode: 'PICKUP' } };
    const res = response(), next = vi.fn();
    await userCheckoutOrder(req, res, next);
    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(201);
    expect(Order.create).toHaveBeenCalledWith([expect.objectContaining({ paidAmount: 0, remainingAmount: 10000, paymentStatus: 'PENDING', countryId: country })]);
    expect(Cart.findOne.mock.calls[0][0]).toHaveProperty('user', buyer);
    expect(JSON.stringify(Cart.findOne.mock.calls[0][0])).toContain(country);
    await userCheckoutOrder({ ...req, body: { amountPaid: 10000 } }, res, next);
    expect(res.status).toHaveBeenLastCalledWith(403);
    expect(Order.create).toHaveBeenCalledOnce();
  });
  it('rejects a sponsored request when the admin disables it', async () => {
    config.getRuntimeConfig.mockResolvedValue(false);
    const res = response();
    await userCheckoutOrder({ user: { _id: buyer }, body: { sponsorship: { payerPhone: '+242060000002' } } }, res, vi.fn());
    expect(res.status).toHaveBeenCalledWith(403);
    expect(Order.create).not.toHaveBeenCalled();
  });
  it.each([true, false])('uses the quoted free-delivery setting after PawaPay confirms (enabled: %s)', async enabled => {
    const amount = enabled ? 10000 : 10750;
    const res = response(), next = vi.fn();
    await pawaPayCheckoutOrder({ user: { _id: buyer }, body: { items: [{ productId, quantity: 1 }], paymentPercent: 100, deliveryMode: 'DELIVERY', shippingAddress: { cityId, communeId, addressLine: 'Rue test', phone: '+242060000001' } }, pawaPayCheckout: { status: 'COMPLETED', amount, checkoutId: 'confirmed', actionContext: { fullPaymentFreeDelivery: enabled } } }, res, next);
    expect(next).not.toHaveBeenCalled();
    expect(res.status).toHaveBeenCalledWith(201);
    expect(Order.create).toHaveBeenCalledWith([expect.objectContaining({ paidAmount: amount, totalAmount: amount, deliveryFeeTotal: enabled ? 0 : 750, deliveryFeeWaived: enabled, paymentStatus: 'PAID_FULL' })], { session: null });
  });
});
