import express from 'express';
import rateLimit from 'express-rate-limit';
import { optionalProtect, protect } from '../middlewares/authMiddleware.js';
import { requireCountryContext } from '../middlewares/countryMiddleware.js';
import { requireFounder, requirePermission } from '../middlewares/roleMiddleware.js';
import { requireShop } from '../controllers/sellerAnalyticsV2Controller.js';
import { requireMessagingEnabled } from '../middlewares/chatSecurity.js';
import { commerceCapabilities, runCommerceAi, founderFinance, recordPlatformExpense } from '../controllers/commerceAiController.js';
const router = express.Router();
router.use(rateLimit({ windowMs: 60000, max: 20, standardHeaders: true, legacyHeaders: false, message: { message: 'Veuillez patienter avant de réessayer.' } }));
router.get('/capabilities', commerceCapabilities);
router.post('/shopping', optionalProtect, requireCountryContext, runCommerceAi('shopping'));
router.post('/complements', optionalProtect, requireCountryContext, runCommerceAi('complements'));
router.post('/coach', protect, requireShop, runCommerceAi('coach'));
router.post('/conversations/:id/reply', protect, requireMessagingEnabled, runCommerceAi('reply'));
router.use('/founder', protect, requireFounder, requirePermission('access_founder_analytics'));
router.get('/founder/finance', founderFinance);
router.post('/founder/expenses', recordPlatformExpense);
router.post('/founder/brief', runCommerceAi('founder'));
export default router;
