import mongoose from 'mongoose';

export const COMMISSION_RATE = 0.03;

export const roundCurrency = (value) => Number(Number(value || 0).toFixed(2));

export const normalizePromoCode = (value) => String(value || '').trim().toUpperCase();

export const generateRandomPromoCode = ({ length = 8, prefix = '' } = {}) => {
  const safeLength = Math.max(4, Math.min(16, Number(length) || 8));
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let i = 0; i < safeLength; i += 1) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  const cleanPrefix = normalizePromoCode(prefix).replace(/[^A-Z0-9]/g, '');
  return cleanPrefix ? `${cleanPrefix}${code}` : code;
};

const toObjectIdString = (value) => {
  if (!value) return '';
  if (value instanceof mongoose.Types.ObjectId) return value.toString();
  return String(value);
};

export const isPromoCodeValidForDate = (promo, at = new Date()) => {
  if (!promo) return false;
  const now = at instanceof Date ? at : new Date(at);
  const starts = promo.startDate ? new Date(promo.startDate) : null;
  const ends = promo.endDate ? new Date(promo.endDate) : null;

  if (!starts || Number.isNaN(starts.getTime())) return false;
  if (!ends || Number.isNaN(ends.getTime())) return false;
  if (starts.getTime() > now.getTime()) return false;
  if (ends.getTime() < now.getTime()) return false;

  return true;
};

export const validatePromoCodeRecord = ({ promo, sellerId, at = new Date() }) => {
  if (!promo) {
    return {
      valid: false,
      reason: 'not_found',
      message: 'Code invalide ou introuvable.'
    };
  }

  if (!promo.isActive) {
    return {
      valid: false,
      reason: 'inactive',
      message: 'Ce code promo est désactivé.'
    };
  }

  if (!isPromoCodeValidForDate(promo, at)) {
    const now = at instanceof Date ? at : new Date(at);
    const starts = promo.startDate ? new Date(promo.startDate) : null;
    const ends = promo.endDate ? new Date(promo.endDate) : null;
    if (starts && starts.getTime() > now.getTime()) {
      return {
        valid: false,
        reason: 'not_started',
        message: 'Ce code promo n’est pas encore actif.'
      };
    }
    return {
      valid: false,
      reason: 'expired',
      message: 'Ce code promo est expiré.'
    };
  }

  if (Number(promo.usedCount || 0) >= Number(promo.usageLimit || 0)) {
    return {
      valid: false,
      reason: 'usage_limit_reached',
      message: 'Ce code promo a atteint sa limite d’utilisation.'
    };
  }

  const seller = toObjectIdString(sellerId);
  const usedBy = Array.isArray(promo.usedBy) ? promo.usedBy.map((item) => toObjectIdString(item)) : [];
  if (seller && usedBy.includes(seller)) {
    return {
      valid: false,
      reason: 'already_used',
      message: 'Vous avez déjà utilisé ce code promo.'
    };
  }

  return { valid: true, reason: 'ok', message: 'Code promo valide.' };
};

export const calculateCommissionBreakdown = ({ productPrice, promo = null }) => {
  const baseAmount = roundCurrency(Number(productPrice || 0) * COMMISSION_RATE);

  if (!promo) {
    return {
      baseAmount,
      discountAmount: 0,
      dueAmount: baseAmount,
      discountRate: 0,
      isWaived: false
    };
  }

  const discountType = promo.discountType;
  let discountRate = 0;

  if (discountType === 'full_waiver') {
    discountRate = 100;
  } else {
    const parsed = Number(promo.discountValue || 0);
    discountRate = Math.max(0, Math.min(100, parsed));
  }

  const discountAmount = roundCurrency((baseAmount * discountRate) / 100);
  const dueAmount = roundCurrency(Math.max(0, baseAmount - discountAmount));

  return {
    baseAmount,
    discountAmount,
    dueAmount,
    discountRate,
    isWaived: dueAmount <= 0
  };
};

export const serializePromoCodeSummary = (promo) => {
  if (!promo) return null;
  return {
    id: promo._id,
    code: promo.code,
    discountType: promo.discountType,
    discountValue: Number(promo.discountValue || 0),
    usageLimit: Number(promo.usageLimit || 0),
    usedCount: Number(promo.usedCount || 0),
    startDate: promo.startDate,
    endDate: promo.endDate,
    isActive: Boolean(promo.isActive),
    referralTag: promo.referralTag || '',
    isFlashPromo: Boolean(promo.isFlashPromo),
    flashDurationHours: promo.flashDurationHours || null,
    autoGenerated: Boolean(promo.autoGenerated)
  };
};
