import React, { useContext, useEffect, useState } from 'react';
import { Link, Navigate, useLocation, useParams } from 'react-router-dom';
import { ArrowPathIcon, CheckCircleIcon, ExclamationCircleIcon, MapPinIcon, ReceiptPercentIcon, ShoppingBagIcon, TruckIcon, XCircleIcon } from '@heroicons/react/24/outline';
import api, { getApiErrorMessage } from '../services/api';
import AuthContext from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import PawaPayButton from '../components/PawaPayButton';
import { useAppSettings } from '../context/AppSettingsContext';
import { ShoppingProgress, shoppingStatus } from '../components/shopping/ShoppingOrderCard';
import ShoppingPrivateImage from '../components/ShoppingPrivateImage';
import ShoppingFinancialStatus from '../components/ShoppingFinancialStatus';
import { formatPriceWithStoredSettings as formatCurrency } from '../utils/priceFormatter';
import { normalizeFileUrl } from '../utils/deliveryUi';

const STATUS_LABEL = {
  SEARCHING_DRIVER: 'Recherche d’un livreur', DRIVER_ASSIGNED: 'Livreur assigné', SHOPPING: 'Achats en cours', WAITING_CUSTOMER_APPROVAL: 'Votre validation est requise', RECEIPT_UPLOADED: 'Reçu ajouté', DELIVERING: 'Livreur en route', DELIVERED: 'Achats livrés', COMPLETED: 'Demande finalisée', CANCELED: 'Demande annulée', FAILED: 'Demande échouée'
};

const estimatedValue = (order) => Number(order?.estimatedShoppingValue || order?.pricing?.estimatedShoppingValue || order?.pricing?.shoppingBudget || order?.maxShoppingBudget || 0);
const authorizedValueLabel = (order) => order?.authorizationMode === 'SHOPPING_BUDGET' || order?.pricing?.authorizationMode === 'SHOPPING_BUDGET'
  ? 'Budget autorisé'
  : 'Valeur estimée';
const balancePreferenceLabel = (preference) => ({
  DRIVER_TIP: 'Pourboire au livreur',
  PLATFORM_DONATION: 'Don à HDMarket',
  WALLET_REFUND: 'Remboursement Mobile Money',
  ORIGINAL_PAYMENT: 'Compte Mobile Money ayant payé'
}[preference] || 'Remboursement Mobile Money');

export default function BuyForMeOrderDetail() {
  const { id } = useParams();
  const location = useLocation();
  const { user } = useContext(AuthContext);
  const { showToast } = useToast();
  const { isFeatureEnabled } = useAppSettings();
  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [replacement, setReplacement] = useState({});
  const [overageAdjustments, setOverageAdjustments] = useState({});
  const [disputeReason, setDisputeReason] = useState('');
  const [loadError, setLoadError] = useState(false);

  const load = () => api.get(`/buy-for-me/mine/${id}`).then(({ data }) => { setOrder(data); setLoadError(false); }).catch(() => setLoadError(true)).finally(() => setLoading(false));
  // load is intentionally re-created with the latest request id.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (user && id) { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); } return undefined; }, [id, user]);
  const post = async (url, body = {}) => { setBusy(true); try { const { data } = await api.post(url, body); setOrder(data); return data; } catch (error) { showToast(getApiErrorMessage(error, 'Action impossible.'), { variant: 'error' }); return null; } finally { setBusy(false); } };
  const respondItem = async (itemId, action) => { const result = await post(`/buy-for-me/mine/${id}/items/${itemId}/respond`, { action, replacementNote: replacement[itemId] || '' }); if (result) showToast('Votre décision a été transmise.', { variant: 'success' }); };
  const setOverageAdjustment = (itemId, action) => setOverageAdjustments((previous) => ({ ...previous, [itemId]: { action, replacementNote: action === 'REPLACE' ? previous[itemId]?.replacementNote || '' : '' } }));
  const submitOverageAdjustments = async () => {
    const adjustments = Object.entries(overageAdjustments).map(([itemId, value]) => ({ itemId, ...value })).filter((value) => ['CANCEL', 'REPLACE'].includes(value.action));
    const result = await post(`/buy-for-me/mine/${id}/overage-adjustments`, { adjustments });
    if (result) { setOverageAdjustments({}); showToast('Vos ajustements ont été envoyés au livreur.', { variant: 'success' }); }
  };

  if (!user) return <Navigate to="/login" state={{ from: location }} replace />;
  if (loading) return <p className="py-12 text-center text-sm text-gray-400">Chargement…</p>;
  if (!order) return <div role="alert" className="shop-error">Impossible de charger cette demande. <button onClick={load} className="underline">Réessayer</button><Link to="/buy-for-me/orders" className="shop-link ml-4">Mes achats</Link></div>;
  const needsAdditionalPayment = !order.disputeOpen && order.status === 'WAITING_CUSTOMER_APPROVAL' && order.additionalPayment?.status === 'REQUIRED';
  const canCancel = !order.disputeOpen && ['SEARCHING_DRIVER', 'DRIVER_ASSIGNED'].includes(order.status);
  const canDispute = !order.disputeOpen && !['PENDING_PAYMENT', 'COMPLETED', 'CANCELED', 'FAILED'].includes(order.status);
  const openDispute = async () => {
    setBusy(true);
    try { await api.post(`/buy-for-me/mine/${id}/disputes`, { reason: disputeReason }); setDisputeReason(''); await load(); }
    catch (error) { showToast(getApiErrorMessage(error, 'Signalement impossible.'), { variant: 'error' }); }
    finally { setBusy(false); }
  };

  return <div className="shop-stack"><div className="shop-row"><div><Link to="/buy-for-me/orders" className="shop-link">← Mes achats</Link><p className="shop-eyebrow">Demande #{String(id).slice(-6).toUpperCase()}</p><h1 className="mt-2">{shoppingStatus(order)}</h1><p className="shop-muted mt-2">{order.preferredStore || 'Magasin au choix du livreur'}</p></div>{['COMPLETED', 'CANCELED', 'FAILED'].includes(order.status) && isFeatureEnabled('enable_buy_for_me', { defaultValue: false }) ? <Link to={'/buy-for-me/new?reorder=' + id} className="shop-button shop-button--secondary">Commander à nouveau</Link> : null}</div>
    <div className="shop-detail-grid"><div className="space-y-4"><section className="shop-card"><h2>De la liste à votre porte</h2><ShoppingProgress order={order} /><p className="shop-muted mt-4">{order.disputeOpen ? 'Notre équipe examine votre signalement.' : order.status === 'DELIVERED' ? 'Vérifiez vos articles et le reçu avant de confirmer.' : order.status === 'WAITING_CUSTOMER_APPROVAL' ? 'Votre livreur attend votre décision pour continuer.' : ['CANCELED', 'FAILED'].includes(order.status) ? 'Cette demande est clôturée. Le suivi financier reste disponible.' : order.status === 'COMPLETED' ? 'Votre demande est terminée. Les remboursements et versements sont suivis séparément.' : 'Retrouvez ici les étapes, les articles et le reçu de votre livreur.'}</p></section>
    {loadError ? <p role="status" className="rounded-xl bg-orange-50 p-3 text-xs text-orange-900">Actualisation impossible. Les dernières informations restent affichées. <button onClick={load} className="underline">Réessayer</button></p> : null}

    {order.additionalPayment?.status === 'PENDING' ? <p role="status" className="rounded-xl bg-orange-50 p-3 text-sm">Paiement complémentaire en cours de vérification. <a className="underline" href={`/payment/pawapay/return?checkoutId=${encodeURIComponent(order.additionalPayment.checkoutId)}`}>Voir le paiement</a></p> : null}
    {order.disputeOpen ? <p role="status" className="rounded-xl border border-orange-200 bg-orange-50 p-3 text-sm font-bold text-orange-900">Votre signalement est en cours d’examen. Les achats et le règlement sont suspendus.</p> : null}
    <section className="rounded-2xl border border-orange-100 bg-orange-50 p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#e85d00]"><ShoppingBagIcon className="h-5 w-5" /></span><div><p className="text-sm font-black text-orange-950">{STATUS_LABEL[order.status] || order.status}</p><p className="mt-0.5 text-xs font-medium text-orange-800">{order.preferredStore || 'Magasin au choix du livreur'} · {authorizedValueLabel(order)} {formatCurrency(estimatedValue(order))}</p></div></div></section>
    <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-black text-gray-900"><MapPinIcon className="text-[#e85d00] h-4 w-4" /> Parcours</h2><div className="mt-3 grid gap-2 text-sm"><p><span className="font-bold text-gray-500">Magasin :</span> {order.pickup?.address}</p><p><span className="font-bold text-gray-500">Livraison :</span> {order.dropoff?.address}</p></div></section>
    <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="text-sm font-black text-gray-900">Liste d’achats</h2><div className="mt-3 space-y-2">{(order.items || []).map((item) => <div key={item._id} className="rounded-xl bg-gray-50 p-3"><div className="flex items-start gap-3">{item.imageUrl ? <a href={normalizeFileUrl(item.imageUrl)} target="_blank" rel="noreferrer" className="shrink-0"><img src={normalizeFileUrl(item.imageUrl)} alt={item.name} className="h-14 w-14 rounded-xl bg-gray-100 object-cover" /></a> : null}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold text-gray-900">{item.name} <span className="text-gray-500">× {item.quantity}</span></p><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-black ${item.status === 'FOUND' ? 'bg-emerald-100 text-emerald-700' : item.status === 'UNAVAILABLE' ? 'bg-orange-100 text-orange-700' : 'bg-gray-200 text-gray-600'}`}>{item.status === 'FOUND' ? 'Trouvé' : item.status === 'UNAVAILABLE' ? 'Indisponible' : item.status === 'CANCELED' ? 'Annulé' : 'À acheter'}</span></div><p className="mt-1 text-xs font-semibold text-gray-600">{item.estimatedUnitPrice > 0 ? `Estimation : ${formatCurrency(item.estimatedUnitPrice)} × ${item.quantity} = ${formatCurrency(item.estimatedTotal)}` : 'Prix à confirmer dans le budget autorisé'}</p>{item.note ? <p className="mt-1 text-xs text-gray-500">{item.note}</p> : null}{item.replacementNote ? <p className="mt-1 text-xs font-semibold text-orange-700">{item.replacementNote}</p> : null}</div></div>{!order.disputeOpen && !['REQUIRED', 'PENDING'].includes(order.additionalPayment?.status) && item.status === 'UNAVAILABLE' && order.status === 'WAITING_CUSTOMER_APPROVAL' ? <div className="mt-3 space-y-2"><input value={replacement[item._id] || ''} onChange={(event) => setReplacement((previous) => ({ ...previous, [item._id]: event.target.value }))} placeholder="Produit de remplacement" className="min-h-10 w-full rounded-lg border border-gray-200 bg-white px-2.5 text-xs outline-none focus:border-[#e85d00]" /><div className="grid grid-cols-3 gap-2"><button disabled={busy} onClick={() => respondItem(item._id, 'REPLACE')} className="rounded-lg bg-[#e85d00] px-2 py-2 text-[10px] font-black text-white">Remplacer</button><button disabled={busy} onClick={() => respondItem(item._id, 'CANCEL')} className="rounded-lg border border-red-200 px-2 py-2 text-[10px] font-black text-red-600">Annuler</button><button disabled={busy} onClick={() => respondItem(item._id, 'CONTINUE')} className="rounded-lg border border-gray-200 px-2 py-2 text-[10px] font-black text-gray-600">Sans lui</button></div></div> : null}</div>)}</div></section>
    {needsAdditionalPayment ? <section className="rounded-2xl border border-orange-200 bg-orange-50 p-4"><p className="flex items-center gap-2 text-sm font-black text-orange-900"><ExclamationCircleIcon className="h-[17px] w-[17px]" /> Le total dépasse votre montant estimé</p><p className="mt-1 text-xs leading-5 text-orange-800">Le livreur ne doit pas avancer la différence. Approuvez le complément de <strong>{formatCurrency(order.additionalPayment.amount)}</strong>, ou ajustez votre liste avant la reprise des achats.</p><div className="mt-3"><PawaPayButton className="shopping-pay" amount={order.additionalPayment.amount} purpose="BUY_FOR_ME_ADDITIONAL_FUNDING" returnPath={`/buy-for-me/${id}`} label="Approuver le paiement complémentaire" actionContext={{ kind: 'BUY_FOR_ME_ADDITIONAL_PAYMENT', orderId: id }} onResult={load} /></div><div className="mt-3 space-y-2 border-t border-orange-200 pt-3"><p className="text-xs font-black text-orange-900">Retirer ou remplacer par une alternative moins chère</p>{(order.items || []).filter((item) => item.status !== 'CANCELED').map((item) => <div key={item._id} className="rounded-xl border border-orange-200 bg-white/80 p-2.5"><p className="text-xs font-bold text-gray-800">{item.name}</p><input value={overageAdjustments[item._id]?.replacementNote || ''} disabled={overageAdjustments[item._id]?.action === 'CANCEL'} onChange={(event) => setOverageAdjustments((previous) => ({ ...previous, [item._id]: { action: 'REPLACE', replacementNote: event.target.value } }))} placeholder="Alternative moins chère" className="mt-2 min-h-9 w-full rounded-lg border border-gray-200 bg-white px-2 text-xs outline-none focus:border-[#e85d00] disabled:bg-gray-100" /><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" disabled={busy} onClick={() => setOverageAdjustment(item._id, 'REPLACE')} className={`rounded-lg border px-2 py-2 text-[10px] font-black ${overageAdjustments[item._id]?.action === 'REPLACE' ? 'border-[#e85d00] bg-orange-100 text-[#a73f00]' : 'border-orange-200 text-orange-800'}`}>Remplacer</button><button type="button" disabled={busy} onClick={() => setOverageAdjustment(item._id, 'CANCEL')} className={`rounded-lg border px-2 py-2 text-[10px] font-black ${overageAdjustments[item._id]?.action === 'CANCEL' ? 'border-red-400 bg-red-50 text-red-700' : 'border-red-200 text-red-600'}`}>Retirer</button></div></div>)}</div><button type="button" disabled={busy || !Object.values(overageAdjustments).some((entry) => ['CANCEL', 'REPLACE'].includes(entry.action))} onClick={submitOverageAdjustments} className="mt-3 min-h-11 w-full rounded-xl bg-[#e85d00] px-3 text-xs font-black text-white disabled:opacity-50">Envoyer les ajustements au livreur</button></section> : null}
    {order.receiptId ? <section className="rounded-2xl border border-violet-100 bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-black text-gray-900"><ReceiptPercentIcon className="text-violet-600 h-4 w-4" /> Reçu du magasin</h2><div className="mt-3 flex items-start gap-3"><ShoppingPrivateImage url={order.receiptId.receiptImageUrl} orderId={id} alt="Reçu du magasin" className="h-16 w-16 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="text-sm font-bold text-gray-900">{order.receiptId.storeName}</p><div className="mt-2 space-y-1 text-xs text-gray-600"><p className="flex justify-between gap-3"><span>{authorizedValueLabel(order)}</span><strong>{formatCurrency(estimatedValue(order))}</strong></p><p className="flex justify-between gap-3"><span>Achats réels</span><strong>{formatCurrency(order.receiptId.amountSpent)}</strong></p><p className="flex justify-between gap-3"><span>Solde restant</span><strong>{formatCurrency(order.remainingBalance)}</strong></p><p className="flex justify-between gap-3"><span>Destination du solde</span><strong className="text-right">{balancePreferenceLabel(order.balancePreference)}</strong></p><p className="flex justify-between gap-3"><span>Frais de livraison</span><strong>{formatCurrency(order.pricing?.deliveryFee)}</strong></p><p className="flex justify-between gap-3"><span>Frais d’avance / retrait</span><strong>{formatCurrency(order.pricing?.cashAdvanceFee)}</strong></p><p className="flex justify-between gap-3"><span>Frais HDMarket</span><strong>{formatCurrency(order.pricing?.serviceCommission)}</strong></p></div></div></div>{order.receiptId.productPhotoUrls?.length ? <div className="mt-3"><p className="text-xs font-bold text-gray-600">Photos des produits</p><div className="mt-2 flex gap-2 overflow-x-auto">{order.receiptId.productPhotoUrls.map((url, index) => <ShoppingPrivateImage key={url} url={url} orderId={id} index={index} alt="Produit acheté" className="h-16 w-16 rounded-lg object-cover" />)}</div></div> : null}</section> : null}
    {!order.disputeOpen && order.status === 'DELIVERED' ? <button disabled={busy} onClick={() => post(`/buy-for-me/mine/${id}/confirm`).then((result) => result && showToast('Merci, la demande est finalisée.', { variant: 'success' }))} className="shop-button w-full"><CheckCircleIcon className="h-[17px] w-[17px]" /> Confirmer la bonne réception</button> : null}
    {canCancel ? <button disabled={busy} onClick={() => post(`/buy-for-me/mine/${id}/cancel`).then((result) => result && showToast('Demande annulée.', { variant: 'success' }))} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-white text-xs font-black text-red-600 disabled:opacity-60"><XCircleIcon className="h-[15px] w-[15px]" /> Annuler la demande</button> : null}
    {canDispute ? <section className="rounded-2xl border border-orange-100 bg-white p-4"><h2 className="text-sm font-black">Un problème avec vos achats ?</h2><label className="mt-2 block text-xs">Décrivez le problème<textarea value={disputeReason} onChange={event => setDisputeReason(event.target.value)} maxLength={1000} rows={3} className="mt-1 w-full rounded-xl border p-3" /></label><button disabled={busy || !disputeReason.trim()} onClick={openDispute} className="mt-2 min-h-11 rounded-xl bg-[#e85d00] px-4 text-sm font-bold text-white disabled:opacity-50">Signaler et suspendre la demande</button></section> : null}
    {(order.disputes || []).map(dispute => <section key={dispute._id} className="rounded-xl border bg-white p-3 text-xs"><p className="font-bold">Votre signalement · {({ OPEN: 'Ouvert', IN_REVIEW: 'En cours d’examen', RESOLVED: 'Résolu', REJECTED: 'Clôturé' })[dispute.status]}</p><p className="mt-1">{dispute.reason}</p>{dispute.resolution ? <p className="mt-2">Réponse : {dispute.resolution}</p> : null}</section>)}
    {order.driverId ? <p className="flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><TruckIcon className="h-[15px] w-[15px]" /> Livreur : {order.driverId.fullName || order.driverId.name || 'attribué'}</p> : null}
  </div><aside className="shop-stack shop-summary"><ShoppingFinancialStatus order={order} /><div className="shop-note"><strong>Un achat, un reçu, un suivi.</strong><p>Tout dépassement du budget nécessite votre accord. Signalez un problème avant de confirmer la bonne réception.</p></div></aside></div></div>;
}
