import React, { useContext, useEffect, useState } from 'react';
import { Navigate, useLocation, useParams } from 'react-router-dom';
import { CheckCircle2, CircleAlert, Loader2, MapPin, ReceiptText, ShoppingBasket, Truck, XCircle } from 'lucide-react';
import api, { getApiErrorMessage } from '../services/api';
import AuthContext from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import PawaPayButton from '../components/PawaPayButton';
import GlassHeader from '../components/orders/GlassHeader';
import { formatPriceWithStoredSettings as formatCurrency } from '../utils/priceFormatter';
import { normalizeFileUrl } from '../utils/deliveryUi';

const STATUS_LABEL = {
  SEARCHING_DRIVER: 'Recherche d’un livreur', DRIVER_ASSIGNED: 'Livreur assigné', SHOPPING: 'Achats en cours', WAITING_CUSTOMER_APPROVAL: 'Votre validation est requise', RECEIPT_UPLOADED: 'Reçu ajouté', DELIVERING: 'Livreur en route', DELIVERED: 'Achats livrés', COMPLETED: 'Demande finalisée', CANCELED: 'Demande annulée', FAILED: 'Demande échouée'
};

const estimatedValue = (order) => Number(order?.estimatedShoppingValue || order?.pricing?.estimatedShoppingValue || order?.pricing?.shoppingBudget || order?.maxShoppingBudget || 0);
const authorizedValueLabel = (order) => order?.authorizationMode === 'SHOPPING_BUDGET' || order?.pricing?.authorizationMode === 'SHOPPING_BUDGET'
  ? 'Budget autorisé'
  : 'Valeur estimée';
const balancePreferenceLabel = (preference) => ({
  DRIVER_TIP: 'Pourboire au livreur',
  PLATFORM_DONATION: 'Don à HDMarket',
  WALLET_REFUND: 'Remboursement portefeuille HDMarket'
}[preference] || 'Remboursement portefeuille HDMarket');

export default function BuyForMeOrderDetail() {
  const { id } = useParams();
  const location = useLocation();
  const { user } = useContext(AuthContext);
  const { showToast } = useToast();
  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [replacement, setReplacement] = useState({});
  const [overageAdjustments, setOverageAdjustments] = useState({});

  const load = () => api.get(`/buy-for-me/mine/${id}`).then(({ data }) => setOrder(data)).catch(() => setOrder(null)).finally(() => setLoading(false));
  // load is intentionally re-created with the latest request id.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { if (user && id) { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); } return undefined; }, [id, user]);
  const post = async (url, body = {}) => { setBusy(true); try { const { data } = await api.post(url, body); setOrder(data); return data; } catch (error) { showToast(getApiErrorMessage(error, 'Action impossible.'), { variant: 'error' }); return null; } finally { setBusy(false); } };
  const respondItem = async (itemId, action) => { const result = await post(`/buy-for-me/mine/${id}/items/${itemId}/respond`, { action, replacementNote: replacement[itemId] || '' }); if (result) showToast('Votre décision a été transmise.', { variant: 'success' }); };
  const setOverageAdjustment = (itemId, action) => setOverageAdjustments((previous) => ({ ...previous, [itemId]: { action, replacementNote: action === 'REPLACE' ? previous[itemId]?.replacementNote || '' : '' } }));
  const submitOverageAdjustments = async () => {
    const adjustments = Object.entries(overageAdjustments).map(([itemId, value]) => ({ itemId, ...value })).filter((value) => ['CANCEL', 'REPLACE'].includes(value.action));
    const result = await post(`/buy-for-me/mine/${id}/overage-adjustments`, { adjustments });
    if (result) { setOverageAdjustments({}); showToast('Vos ajustements ont été envoyés au livreur.', { variant: 'success' }); }
  };

  if (!user) return <Navigate to="/login" state={{ from: location }} replace />;
  if (loading) return <p className="py-12 text-center text-sm text-gray-400">Chargement…</p>;
  if (!order) return <p className="py-12 text-center text-sm text-gray-400">Demande introuvable.</p>;
  const needsAdditionalPayment = order.additionalPayment?.status === 'REQUIRED';
  const canCancel = ['SEARCHING_DRIVER', 'DRIVER_ASSIGNED'].includes(order.status) || needsAdditionalPayment;

  return <div className="min-h-screen bg-[#faf8f5] pb-12"><GlassHeader title="Suivi des achats" subtitle={STATUS_LABEL[order.status] || order.status} backTo="/buy-for-me/orders" /><div className="mx-auto max-w-lg space-y-3 px-4 py-4">
    <section className="rounded-2xl border border-orange-100 bg-orange-50 p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-[#e85d00]"><ShoppingBasket size={20} /></span><div><p className="text-sm font-black text-orange-950">{STATUS_LABEL[order.status] || order.status}</p><p className="mt-0.5 text-xs font-medium text-orange-800">{order.preferredStore || 'Magasin au choix du livreur'} · {authorizedValueLabel(order)} {formatCurrency(estimatedValue(order))}</p></div></div></section>
    <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-black text-gray-900"><MapPin size={16} className="text-[#e85d00]" /> Parcours</h2><div className="mt-3 grid gap-2 text-sm"><p><span className="font-bold text-gray-500">Magasin :</span> {order.pickup?.address}</p><p><span className="font-bold text-gray-500">Livraison :</span> {order.dropoff?.address}</p></div></section>
    <section className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm"><h2 className="text-sm font-black text-gray-900">Liste d’achats</h2><div className="mt-3 space-y-2">{(order.items || []).map((item) => <div key={item._id} className="rounded-xl bg-gray-50 p-3"><div className="flex items-start gap-3">{item.imageUrl ? <a href={normalizeFileUrl(item.imageUrl)} target="_blank" rel="noreferrer" className="shrink-0"><img src={normalizeFileUrl(item.imageUrl)} alt={item.name} className="h-14 w-14 rounded-xl bg-gray-100 object-cover" /></a> : null}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold text-gray-900">{item.name} <span className="text-gray-500">× {item.quantity}</span></p><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-black ${item.status === 'FOUND' ? 'bg-emerald-100 text-emerald-700' : item.status === 'UNAVAILABLE' ? 'bg-orange-100 text-orange-700' : 'bg-gray-200 text-gray-600'}`}>{item.status === 'FOUND' ? 'Trouvé' : item.status === 'UNAVAILABLE' ? 'Indisponible' : item.status === 'CANCELED' ? 'Annulé' : 'À acheter'}</span></div><p className="mt-1 text-xs font-semibold text-gray-600">{item.estimatedUnitPrice > 0 ? `Estimation : ${formatCurrency(item.estimatedUnitPrice)} × ${item.quantity} = ${formatCurrency(item.estimatedTotal)}` : 'Prix à confirmer dans le budget autorisé'}</p>{item.note ? <p className="mt-1 text-xs text-gray-500">{item.note}</p> : null}{item.replacementNote ? <p className="mt-1 text-xs font-semibold text-orange-700">{item.replacementNote}</p> : null}</div></div>{item.status === 'UNAVAILABLE' && order.status === 'WAITING_CUSTOMER_APPROVAL' ? <div className="mt-3 space-y-2"><input value={replacement[item._id] || ''} onChange={(event) => setReplacement((previous) => ({ ...previous, [item._id]: event.target.value }))} placeholder="Produit de remplacement" className="min-h-10 w-full rounded-lg border border-gray-200 bg-white px-2.5 text-xs outline-none focus:border-[#e85d00]" /><div className="grid grid-cols-3 gap-2"><button disabled={busy} onClick={() => respondItem(item._id, 'REPLACE')} className="rounded-lg bg-[#e85d00] px-2 py-2 text-[10px] font-black text-white">Remplacer</button><button disabled={busy} onClick={() => respondItem(item._id, 'CANCEL')} className="rounded-lg border border-red-200 px-2 py-2 text-[10px] font-black text-red-600">Annuler</button><button disabled={busy} onClick={() => respondItem(item._id, 'CONTINUE')} className="rounded-lg border border-gray-200 px-2 py-2 text-[10px] font-black text-gray-600">Sans lui</button></div></div> : null}</div>)}</div></section>
    {needsAdditionalPayment ? <section className="rounded-2xl border border-orange-200 bg-orange-50 p-4"><p className="flex items-center gap-2 text-sm font-black text-orange-900"><CircleAlert size={17} /> Le total dépasse votre montant estimé</p><p className="mt-1 text-xs leading-5 text-orange-800">Le livreur ne doit pas avancer la différence. Approuvez le complément de <strong>{formatCurrency(order.additionalPayment.amount)}</strong>, ou ajustez votre liste avant la reprise des achats.</p><div className="mt-3"><PawaPayButton amount={order.additionalPayment.amount} purpose="BUY_FOR_ME_ADDITIONAL_FUNDING" returnPath={`/buy-for-me/${id}`} label="Approuver le paiement complémentaire" actionContext={{ kind: 'BUY_FOR_ME_ADDITIONAL_PAYMENT', orderId: id }} /></div><div className="mt-3 space-y-2 border-t border-orange-200 pt-3"><p className="text-xs font-black text-orange-900">Retirer ou remplacer par une alternative moins chère</p>{(order.items || []).filter((item) => item.status !== 'CANCELED').map((item) => <div key={item._id} className="rounded-xl border border-orange-200 bg-white/80 p-2.5"><p className="text-xs font-bold text-gray-800">{item.name}</p><input value={overageAdjustments[item._id]?.replacementNote || ''} disabled={overageAdjustments[item._id]?.action === 'CANCEL'} onChange={(event) => setOverageAdjustments((previous) => ({ ...previous, [item._id]: { action: 'REPLACE', replacementNote: event.target.value } }))} placeholder="Alternative moins chère" className="mt-2 min-h-9 w-full rounded-lg border border-gray-200 bg-white px-2 text-xs outline-none focus:border-[#e85d00] disabled:bg-gray-100" /><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" disabled={busy} onClick={() => setOverageAdjustment(item._id, 'REPLACE')} className={`rounded-lg border px-2 py-2 text-[10px] font-black ${overageAdjustments[item._id]?.action === 'REPLACE' ? 'border-[#e85d00] bg-orange-100 text-[#a73f00]' : 'border-orange-200 text-orange-800'}`}>Remplacer</button><button type="button" disabled={busy} onClick={() => setOverageAdjustment(item._id, 'CANCEL')} className={`rounded-lg border px-2 py-2 text-[10px] font-black ${overageAdjustments[item._id]?.action === 'CANCEL' ? 'border-red-400 bg-red-50 text-red-700' : 'border-red-200 text-red-600'}`}>Retirer</button></div></div>)}</div><button type="button" disabled={busy || !Object.values(overageAdjustments).some((entry) => ['CANCEL', 'REPLACE'].includes(entry.action))} onClick={submitOverageAdjustments} className="mt-3 min-h-11 w-full rounded-xl bg-[#e85d00] px-3 text-xs font-black text-white disabled:opacity-50">Envoyer les ajustements au livreur</button></section> : null}
    {order.receiptId ? <section className="rounded-2xl border border-violet-100 bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 text-sm font-black text-gray-900"><ReceiptText size={16} className="text-violet-600" /> Reçu du magasin</h2><div className="mt-3 flex items-start gap-3"><a href={normalizeFileUrl(order.receiptId.receiptImageUrl)} target="_blank" rel="noreferrer" className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-xl bg-violet-50 text-violet-600">{order.receiptId.receiptImageUrl ? <img src={normalizeFileUrl(order.receiptId.receiptImageUrl)} alt="Reçu" className="h-full w-full object-cover" /> : <ReceiptText />}</a><div className="min-w-0 flex-1"><p className="text-sm font-bold text-gray-900">{order.receiptId.storeName}</p><div className="mt-2 space-y-1 text-xs text-gray-600"><p className="flex justify-between gap-3"><span>{authorizedValueLabel(order)}</span><strong>{formatCurrency(estimatedValue(order))}</strong></p><p className="flex justify-between gap-3"><span>Achats réels</span><strong>{formatCurrency(order.receiptId.amountSpent)}</strong></p><p className="flex justify-between gap-3"><span>Solde restant</span><strong>{formatCurrency(order.remainingBalance)}</strong></p><p className="flex justify-between gap-3"><span>Destination du solde</span><strong className="text-right">{balancePreferenceLabel(order.balancePreference)}</strong></p><p className="flex justify-between gap-3"><span>Frais de livraison</span><strong>{formatCurrency(order.pricing?.deliveryFee)}</strong></p><p className="flex justify-between gap-3"><span>Frais d’avance / retrait</span><strong>{formatCurrency(order.pricing?.cashAdvanceFee)}</strong></p><p className="flex justify-between gap-3"><span>Frais HDMarket</span><strong>{formatCurrency(order.pricing?.serviceCommission)}</strong></p></div></div></div>{order.receiptId.productPhotoUrls?.length ? <div className="mt-3"><p className="text-xs font-bold text-gray-600">Photos des produits</p><div className="mt-2 flex gap-2 overflow-x-auto">{order.receiptId.productPhotoUrls.map((url) => <a key={url} href={normalizeFileUrl(url)} target="_blank" rel="noreferrer" className="shrink-0"><img src={normalizeFileUrl(url)} alt="Produit acheté" className="h-16 w-16 rounded-lg object-cover" /></a>)}</div></div> : null}</section> : null}
    {order.status === 'DELIVERED' ? <button disabled={busy} onClick={() => post(`/buy-for-me/mine/${id}/confirm`).then((result) => result && showToast('Merci, la demande est finalisée.', { variant: 'success' }))} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-black text-white disabled:opacity-60"><CheckCircle2 size={17} /> Confirmer la bonne réception</button> : null}
    {canCancel ? <button disabled={busy} onClick={() => post(`/buy-for-me/mine/${id}/cancel`).then((result) => result && showToast('Demande annulée.', { variant: 'success' }))} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-white text-xs font-black text-red-600 disabled:opacity-60"><XCircle size={15} /> Annuler la demande</button> : null}
    {order.driverId ? <p className="flex items-center gap-2 rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700"><Truck size={15} /> Livreur : {order.driverId.fullName || order.driverId.name || 'attribué'}</p> : null}
  </div></div>;
}
