import mongoose from 'mongoose';

const promoCodeSchema = new mongoose.Schema(
  {
    code: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      uppercase: true,
      minlength: 3,
      maxlength: 40,
      index: true
    },
    discountType: {
      type: String,
      enum: ['percentage', 'full_waiver'],
      required: true
    },
    discountValue: {
      type: Number,
      min: 0,
      max: 100,
      default: 0
    },
    usageLimit: {
      type: Number,
      required: true,
      min: 1
    },
    usedCount: {
      type: Number,
      default: 0,
      min: 0
    },
    usedBy: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
    startDate: {
      type: Date,
      required: true
    },
    endDate: {
      type: Date,
      required: true,
      index: true
    },
    isActive: {
      type: Boolean,
      default: true,
      index: true
    },
    autoGenerated: {
      type: Boolean,
      default: false
    },
    referralTag: {
      type: String,
      trim: true,
      default: ''
    },
    isFlashPromo: {
      type: Boolean,
      default: false
    },
    flashDurationHours: {
      type: Number,
      min: 1,
      max: 720,
      default: null
    },
    totalCommissionWaived: {
      type: Number,
      min: 0,
      default: 0
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },
    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null
    },
    deactivatedAt: {
      type: Date,
      default: null
    },
    deactivatedReason: {
      type: String,
      enum: [null, 'manual', 'usage_limit_reached', 'expired'],
      default: null
    }
  },
  { timestamps: true }
);

promoCodeSchema.index({ code: 1 }, { unique: true });
promoCodeSchema.index({ isActive: 1, endDate: 1 });

promoCodeSchema.pre('validate', function (next) {
  if (this.code) {
    this.code = this.code.trim().toUpperCase();
  }

  if (this.discountType === 'full_waiver') {
    this.discountValue = 100;
  }

  if (this.discountType === 'percentage') {
    if (!Number.isFinite(this.discountValue) || this.discountValue <= 0 || this.discountValue > 100) {
      return next(new Error('discountValue must be between 0 and 100 for percentage discounts.'));
    }
  }

  if (
    this.startDate instanceof Date &&
    this.endDate instanceof Date &&
    this.startDate.getTime() >= this.endDate.getTime()
  ) {
    return next(new Error('endDate must be after startDate.'));
  }

  if (Number(this.usedCount || 0) > Number(this.usageLimit || 0)) {
    return next(new Error('usedCount cannot exceed usageLimit.'));
  }

  return next();
});

export default mongoose.model('PromoCode', promoCodeSchema);
